#!/bin/bash

#SBATCH --open-mode=truncate
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=16
#SBATCH --constraint=EPYC_7763
#SBATCH --job-name=16coreUpTo13
#SBATCH --time=72:00:00

module load gcc/6.3.0
module load netlib-lapack/3.9.1
module load openblas/0.3.20
module load openmpi/4.1.4
export OMP_NUM_THREADS=16

python3 scripts/plotting.py